name: output-actions
on: workflow_dispatch
jobs:
    output:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: output message
              run: echo "${{ toJSON(github) }}"